name: Generate Snake Animation 🐍

on:
  schedule:
    - cron: "0 0 * * *"  # كل يوم
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate the snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: AliDev
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Push the changes
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
